name: tasks_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  flutter_statusbarcolor: ^0.2.3
  
  feather_icons_flutter: ^4.7.4

  sqflite: ^1.3.1+1
  path_provider: ^1.4.0

  androidish_ink_well: ^2.0.0
  provider: ^4.3.2
  pie_chart: ^4.0.1
  line_icons: ^0.2.0
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  uuid: ^2.2.0
  shared_preferences: '>=0.5.8 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launch_icon_white.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon-green.png

  fonts:
    - family: Gellix
      fonts:
        - asset: assets/fonts/GellixBlack.otf
          weight: 900
        - asset: assets/fonts/GellixExtraBold.otf
          weight: 800
        - asset: assets/fonts/GellixBold.otf
          weight: 700
        - asset: assets/fonts/GellixSemiBold.otf
          weight: 600
        - asset: assets/fonts/GellixMedium.otf
          weight: 500
        - asset: assets/fonts/GellixRegular.otf
          weight: 400
        - asset: assets/fonts/GellixLight.otf
          weight: 300
        - asset: assets/fonts/GellixThin.otf
          weight: 200
